<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD4AxehU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD4AxehU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD4AxehU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD4AxehU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD4AxehU\App_KernelDevDebugContainer([
    'container.build_hash' => 'D4AxehU',
    'container.build_id' => 'e532efc4',
    'container.build_time' => 1696368378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD4AxehU');
